### PR TITLE
Create PDA-compatible revert-button-style script

### PR DESCRIPTION
**Pull request by Kwack-Kwack**
Hey,

Glad I found this script already written, I was about to write it myself (was looking for the old css...)
I just thought I'd submit a PR containing a [torn PDA](https://github.com/Manuito83/torn-pda)-compatible version as I've had people request a similar script there. Note that PDA doesn't support the updateURL parameter as well.

If you think it's out of scope for this repo I'm happy to host it seperately. Cheers.

### CODE REVIEW

**Comment by Kwack-Kwack** [comment]
Note for this script you may also wish to eventually hard-code the variables torn uses rather than rely on them not changing/removing the old variables

**Comment by br41nslug** [comment]
Oh awesome, havent used TornPDA in a while myself but definitely up for getting that compatible.

> Note for this script you may also wish to eventually hard-code the variables torn uses rather than rely on them not changing/removing the old variables

Yeah was thinking the same and did some of the variable work in the latest update.

**Comment by br41nslug** [comment]
Updated the script with my latest changes 🚀 will install tornpda and test if it works as expected tomorrow

**Comment by br41nslug** [comment]
Cant say i've tested super extensively but seems to work on the pages i've opened

**Pull request merged**
